language: cpp
dist: bionic
addons:
  apt:
    packages:
      - cmake
      - g++-7
      - g++-8
      - clang-5.0
      - clang-6.0
      - shunit2
      - ninja-build
      - python3
      - python3-pip
      - python3-setuptools
  homebrew:
    packages:
      - ninja
      - shunit2
    # temporary workaround for this problem
    # https://travis-ci.community/t/macos-build-fails-because-of-homebrew-bundle-unknown-command/7296/10
    update: true

os: linux
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
  - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
  - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      compiler: clang
      env:
        - MATRIX_EVAL=""

    - os: osx
      name: osx integration tests
      osx_image: xcode10.2
      compiler: clang
      env:
        - MATRIX_EVAL=""
      script:
        - "./test/installation-tests.sh"
        - "./test/compilation-tests.sh"

    - os: linux
      name: linux integration tests
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      script:
        - "./test/version-consistency.sh"
        - "./test/installation-tests.sh"
        - "./test/compilation-tests.sh"

    - if: type = pull_request OR branch = master OR tag IS present
      os: linux
      name: version consistency check
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      script:
        - "./test/version-consistency.sh"

    - stage: deploy-unstable
      os: linux
      env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      script:
        - conan remote add bernedom https://api.bintray.com/conan/bernedom/conan
        - conan create . SI/unstable
        - conan upload SI/*@SI/unstable --all -c -r bernedom

    - stage: deploy-stable
      os: linux
      env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      script:
        - conan remote add bernedom https://api.bintray.com/conan/bernedom/conan
        - conan create . SI/stable
        - conan upload SI/*@SI/stable --all -c -r bernedom

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - pip3 install conan

script:
  - cmake --version
  - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug -G Ninja
  - cmake --build . --config Debug
  - ctest -C Debug

stages:
  - Test
  - name: deploy-unstable
    if: branch = master AND type NOT IN (pull_request) AND tag IS NOT present
  - name: deploy-stable
    if: type NOT IN (pull_request) AND tag IS present AND tag ~= /^[0-9]+\.[0-9]+\.[0-9]+$/
